//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE #CountryByCity(
        ///	[Country] [nvarchar](255) NOT NULL,
        ///	[CountryCode] [nvarchar](255) NOT NULL,
        ///	[City] [nvarchar](255) NOT NULL
        ///)
        ///
        ///INSERT #CountryByCity (Country, CountryCode, City) VALUES
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Alajuela&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Alajuelita&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Ángeles&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Aserrí&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Atenas&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Bagaces&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Batán&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Bejuco&apos;),
        ///(N&apos;Costa Rica&apos;,N&apos;CR&apos;,N&apos;Be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryByCity {
            get {
                return ResourceManager.GetString("CountryByCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO REGION 
        ///SELECT DISTINCT NULL AS ParentId, Country AS Name, &apos;Country&apos; AS RegionType
        ///FROM #CountryByCity
        ///
        ///
        ///INSERT INTO REGION 
        ///SELECT DISTINCT Id AS ParentId, City AS Name, &apos;City&apos; AS RegionType
        ///FROM #CountryByCity
        ///JOIN Region ON Name = Country
        ///	AND RegionType = &apos;Country&apos;.
        /// </summary>
        internal static string InsertRegions {
            get {
                return ResourceManager.GetString("InsertRegions", resourceCulture);
            }
        }
    }
}
